### ISSUE TITLE
nobody can skid!1!1!1!!!

### ISSUE THREAD

**Issue by ChompChompDead** [ciruu1/InstantBurrow#2]
y would u want people to skid this if you have like external files needed for this lmao

**Comment by ciruu1** [comment]
LOL it is not my problem. Code the needed stuff by yourself, i just only gave the method of how the module works.

**Comment by pastimee** [comment]
how are you so retarded that you can't skid bc it needs other utils

**Comment by ciruu1** [comment]
Oh my god, you only need an util to place a block and change the slot in hotbar, nothing more. I even commented the code. Please read before.
